version: "3.1"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    user: '0:0'
    container_name: sqlserver2017
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PasswordO1.
      MSSQL_PID: Express
    volumes:
      - ~/docker/sqlserver-data:/var/opt/mssql
