version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - /var/www/html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - applaravel
      - mysql
    networks:
      - networkapp

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: name_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: db_root_password
    ports:
      - 33069:3306
    volumes:
      - dbdatalaravel:/var/lib/mysql
    networks:
      - networkapp
  
  sqlserver:
      build: ./sqlserver
      hostname: 'sqlserver'
      environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: Admin@12345
      ports:
        - 1433:1433
      volumes:
        - ms-sqlserver-data:/var/opt/mssql
    networks:
      - networkapp
  
  applaravel:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./php/Dockerfile
    container_name: applaravel
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - networkapp

networks: 
  networkapp:


volumes: 
    dbdatalaravel:
    ms-sqlserver-data:
      driver: local